version: '2.1'

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    depends_on:
        db:
            condition: service_healthy
