# Generated by Django 2.2.4 on 2019-08-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_squashed_0008_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
