# Generated by Django 2.2.4 on 2019-08-07 18:05

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='details',
            field=django_extensions.db.fields.json.JSONField(default=dict),
        ),
    ]
