# Generated by Django 2.2.4 on 2019-08-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AlterField(
            model_name='movie',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
