# Generated by Django 2.2.4 on 2019-08-08 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190807_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
