# Generated by Django 2.2.4 on 2019-08-08 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190808_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
